python: ['python-packages']
contracts: ['contracts']
@powerchain/sol-doc: ['packages/sol-doc']
@powerchain/sol-resolver: ['packages/sol-resolver']
@powerchain/contracts-gen: ['packages/contracts-gen']
@powerchain/sra-spec: ['packages/sra-spec']
@powerchain/subproviders: ['packages/subproviders']
@powerchain/contract-addresses: ['packages/contract-addresses']
@powerchain/migrations: ['packages/migrations']
@powerchain/web3-wrapper: ['packages/web3-wrapper']
@powerchain/sol-compiler: ['packages/sol-compiler']
@powerchain/types: ['packages/types']
@powerchain/instant: ['packages/instant']
@powerchain/abi-gen-templates: ['packages/abi-gen-templates']
@powerchain/abi-gen: ['packages/abi-gen']
@powerchain/sol-coverage: ['packages/sol-coverage']
@powerchain/sol-profiler: ['packages/sol-profiler']
@powerchain/sol-trace: ['packages/sol-trace']
@powerchain/sol-tracing-utils: ['packages/sol-tracing-utils']
@powerchain/utils: ['packages/utils']
@powerchain/tslint-config: ['packages/tslint-config']
@powerchain/asset-swapper: ['packages/asset-swapper']
@powerchain/order-utils: ['packages/order-utils']
@powerchain/assert: ['packages/assert']
@powerchain/base-contract: ['packages/base-contract']
@powerchain/typescript-typings: ['packages/typescript-typings']
powerchain.js: ['packages/powerchain.js']
@powerchain/contract-artifacts: ['packages/contract-artifacts']
@powerchain/dev-utils: ['packages/dev-utils']
@powerchain/contract-wrappers: ['packages/contract-wrappers']
@powerchain/json-schemas: ['packages/json-schemas']
@powerchain/ethereum-types: ['ethereum-types']
@powerchain/connect: ['packages/connect']
