#!/usr/bin/env bash

# extract package interdependencies and topographically sort them

find -name setup.py -exec grep -H \"powerchain- {} \; | \
    grep -v name= | \
    grep -v NAME | \
    sed \
        -e 's/^\.\//powerchain-/' \
        -e 's/\/setup.py://' \
        -e 's/"//g' -e 's/,$//' \
        -e 's/_/-/g' | \
    tsort | \
    tac | \
    sed \
        -e 's/^powerchain-//' \
        -e 's/-/_/'
